### ISSUE TITLE
Add documentation on how to download measurement data

### ISSUE THREAD

**Issue by bjsilver** [openaq/openaq-python#11]
### Description

Hello sorry for asking something so basic but I can't seem to obtain any measurement data using the Python wrapper. I have successfully downloaded a list of all the OpenAQ locations, but the client.Measurements class appears to not have any 'get' method only list. Could you add some guidance on how to download measurements to the documentation please? For example, when I know the location_id, how do I download all the historical data for that location? Many thanks

**Comment by russbiggs** [comment]
Measurements are only available with the `list` method because there is rarely a case when a single measurement is need. You can see a bit more in the reference docs about how to use the measurements list, which requires a `location_id` argument. Then use a `date_from` and `date_to` and `parameters_id` to filter to period and parameter of interest:

https://python.openaq.org/reference/openaq/#openaq._sync.models.measurements.Measurements.list

I will mention this call will change greatly in the future in favor of a "sensor-first" approach. We will still likely provide the location based approach but it will likely get another function name. All that is to say, we will likely document better when the function changes are done. see more in https://github.com/openaq/openaq-python/issues/9

**Comment by bjsilver** [comment]
Thankyou! Sorry I'd misunderstood the difference between list and get
